# Generated by Django 5.2.4 on 2025-07-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_linsting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Linsting',
            new_name='Listing',
        ),
    ]
