# Generated by Django 5.2.4 on 2025-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_active_band_biograohy_band_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='official_homePage',
            field=models.URLField(max_length=100),
        ),
    ]
