# Generated by Django 5.2.4 on 2025-07-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_band_active_alter_band_official_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='biograohy',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='official_homePage',
            new_name='official_homepage',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='yeard_formed',
            new_name='year_formed',
        ),
    ]
